Categories
dev-mission/sfdreamer pull request #37
Opened 2021-08-10 01:14 UTC by JesusEArambula

Added some of the UI designing for the Home and About pages. Links from Home page don't route to anywhere. Also changed some of the styling for Resources page.

2021-08-10 17:04 UTC, francisli commented
@JesusEArambula next time, after you see that a previous pull request has been merged, please remember to CREATE A NEW BRANCH from master, instead of continuing to work in the same branch. 

Branches should only exist for as long as they are needed to develop a new feature, have it reviewed, then merged. 

One of the big reasons to do this is because nowthis pull request contains BOTH the work you did previously (which has ALREADY been merged) AND the new work you did. So it makes it harder for me to just review the NEW work that you did since it's all mixed up together.

It also means that you missed on some changes on the master branch that are now causing the CONFLICTS that you see on your branch. By making sure you start a new branch on master, and keeping the lifetime of a branch limited, you reduce the changes for conflicting changes.

I will help resolve the conflicts on the branch. Again, this is adding more time/work on the reviewer's side since you didn't create a new branch from master. Then I will review the changes and provide feedback...

2021-08-10 18:02 UTC, francisli requested changes
I've added comments to the PR for you to review...

The big change to make is to NOT hard-code the categories into the components, but use the API to load them from the database, and then use JavaScript/React to render the links in the header and the cards on the homepage DYNAMICALLY...

That way, if a category is created/updated/deleted from the database, the site will dynamically be updated, rather than having to edit the code and redeploy... that is the goal of why we did all this work to create the Category model...!

2021-08-10 18:02 UTC, francisli commented on client/src/Home.js
> +        <Link onClick={() => setActive(false)} to="/resources">
You've done a good job of styling the cards... but the goal is not to hard-code the categories, but to load them from the database and use code to generate the cards...!

2021-08-10 18:05 UTC, francisli commented
I see that in your hard-coded links, you've used urls for the categories like `/housing`, `/employment`, etc... if we want to be able to identify a category by a human-readable identifier like that, then we need to add it to the database- otherwise, right now the primary key ids in the database are numbers (i.e. 1, 2, 3, etc).

I'll add a migration to add a new column in the Categories table so that we can add this... sometimes called the "url slug" and then we can look up the category by that name in the database...

2021-08-10 18:27 UTC, francisli commented
Ok, I've pushed up code that adds a unique url slug column to the Category model... make sure to log into the running server container and run `sequelize db:migrate` to make sure it gets added...

2021-08-12 23:57 UTC, francisli commented
@haikelfd you merged your branch in but you didn't address my comments- why is there a dollar sign in front of the category names in the header?

2021-08-13 00:10 UTC, francisli commented
@haikelfd I'm going to go ahead and remove that dollar sign from the header links...

2021-08-13 00:17 UTC, francisli approved these changes
Alright, let's merge and deploy where we are now to see how things are looking...!

2021-08-13 00:18 UTC, merged

2021-08-13 00:47 UTC, haikelfd commented
@francisli, I'm facing a problem with my PC and I have limited access to the connection.  I tried to rewrite it with my MacBook. Which doesn't have the required specs to install a docker to test it out.  Hopefully, the heat problem will go away by next week and the blackouts will end. I will continue working on the website even after the intern ends.

2021-08-13 22:10 UTC, francisli commented
@haikelfd ok, no worries, hope things get better with heat and power back home...!